In [2]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler

#importing datasets
data_set = pd.read_csv(r"C:\Users\User\Downloads\Loan_Approval_Prediction.csv")

data_set.head(5)

Matplotlib is building the font cache; this may take a moment.


Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [5]:
data_set.loc[data_set['Loan_Status'] == 'Y', 'Loan_approval'] = 1
data_set.loc[data_set['Loan_Status'] == 'N', 'Loan_approval'] = 0
data_set.loc[data_set['Education'] == 'Graduate', 'Edu'] = 1
data_set.loc[data_set['Education'] == 'Not Graduate', 'Edu'] = 0
data_set.loc[data_set['Self_Employed'] == 'No', 'Self_Emp'] = 1
data_set.loc[data_set['Self_Employed'] == 'Yes', 'Self_Emp'] = 0
data_set.head()


Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  Loan_approval  Edu  Self_Emp  
0             1.0         Urban           Y            1.0  1.0       1.0  
1             1.0         Rural           N            0.0  1.0       1.0  
2             1.0         Urban           Y            1.0  1.0       0.0  
3             1.0         Urban           Y            1.0  0.0       1.0  
4             1.0         Urban           Y            1.0  1.0       1.0

In [6]:
#Making a new column based on summation of salaries of applicants
data_set['Total Income'] = (data_set['ApplicantIncome'] + data_set['CoapplicantIncome'])
data_set.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  Loan_approval  Edu  Self_Emp  \
0             1.0         Urban           Y            1.0  1.0       1.0   
1             1.0         Rural           N            0.0  1.0       1.0   
2             1.0         Urban           Y            1.0  1.0       0.0   
3             1.0         Urban           Y            1.0  0.0       1.0   
4             1.0         Urban           Y            1.0  1.0       1.0   

   Total Income  
0        5849.0  
1        6091.0  
2        3000.0  
3        4941.0  
4        6000.0

In [7]:
##Handling the missing data with 0 value
data_set = data_set.fillna(0)

In [8]:
#Extracting independant and dependant variable
x = data_set.iloc[:, [14,15,16]].values
y = data_set.iloc[:, 13].values


In [9]:
#Splitting the dataset into training and test set
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=42)


In [10]:
#feature scaling
st_x = StandardScaler()
x_train = st_x.fit_transform(x_train)
x_test = st_x.transform(x_test)
y_test


array([1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1.,
       0., 0., 0., 1., 1., 0., 1., 1., 0., 1., 1., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 1., 0., 1., 1., 0., 0., 1., 1., 1., 1., 1.,
       0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 0., 1., 0., 0., 1.,
       1., 1., 0., 1., 0., 0., 0., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 1., 1., 0., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1.,
       1., 1., 1., 1., 0., 1., 1., 1., 0., 0., 1., 0., 1., 1., 1., 0., 1.,
       1., 1., 1., 0., 1., 1., 0., 0., 1., 1., 1., 0., 1., 1., 1., 1., 0.,
       0.])

In [11]:
knn = KNeighborsClassifier(n_neighbors = 5, metric = 'euclidean')
knn.fit(x_train, y_train)


KNeighborsClassifier(metric='euclidean')

In [12]:
y_pred = knn.predict(x_test)

In [13]:
confusion_matrix(y_test, y_pred)

array([[ 9, 45],
       [13, 87]], dtype=int64)

In [14]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.6233766233766234

In [15]:
from sklearn.metrics import precision_recall_fscore_support
precision_recall_fscore_support(y_test, y_pred)


(array([0.40909091, 0.65909091]),
 array([0.16666667, 0.87      ]),
 array([0.23684211, 0.75      ]),
 array([ 54, 100], dtype=int64))

In [16]:
from sklearn.metrics import precision_score
precision_score(y_test, y_pred)

0.6590909090909091

In [17]:
from sklearn.metrics import recall_score
recall_score(y_test, y_pred)


0.87

In [18]:
from sklearn.metrics import f1_score
f1_score(y_test, y_pred)


0.75